config/routes.rb
Rails.application.routes.draw do

    resources :events do
    
    resources :attendees , controller: "event_attendees"
    
    resource :location, controller: "event_locations"

    collection do
        get :latest
    end

    collection do
      post :bulk_delete
    end

    collection do
      post :bulk_update
    end

    member do
      get :dashboard
    end

    member do
      post :join
      post :withdraw
    end

  end

  resources :people #此為建立應架(scaffold)時自動產生

  get "/welcome/say_hello" => "welcome#say" 
  
  root "welcome#index"

  get "/welcome" => "welcome#index"
  

  namespace :admin do
    resources :events
  end

end

app/controllers/event_attendees_controller.rb
#Restful綜合應用實作
class EventAttendeesController < ApplicationController
	before_action :find_event

	def index
		@attendees = @event.attendees
	end

	def show
		@attendee = @event.attendees.find(params[:id])
	end

	def new
		@attendee = @event.attendees.build	
	end

	def create
		@attendee = @event.attendees.build(attendee_params)
		if @attendee.save
			redirect_to event_attendees_url(@event)
		else
			render action: :new
		end
	end

	def edit
		@attendee = @event.attendees.find(params[:id])
	end

	def update
		@attendee = @event.attendees.find(paramsp[:id])

		if @attendee.update(attendee_params)
			redirect_to event_attendees_url(@event)
		else
			render action: :edit
		end
	end

	def destroy
		@attendee = @event.attendees.find(params[:id])
		@attendee.destroy

		redirect_to event_attendees_url(@event)
	end

	protected

	def find_event
		@event = Event.find(params[:event_id])			
	end

	def attendee_params
		params.require(:attendee).permit(:name)
	end
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/views/event_attendees/edit.html.erb
<!--Restful綜合應用實作-->

<%= form_for @attendee,url: event_attendee_path(@event ,@attendee),html: {method: :patch} do |f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_attendees/index.html.erb
<!--Restful綜合應用實作-->

<ul>
	<% @attendees.each do |attendee| %>
	<li>
		<%= attendee.name %>
		<%= link_to "show",event_attendee_path(@event ,attendee) %>
		<%= link_to "edit",edit_event_attendee_path(@event,attendee) %>
		<%= link_to "destroy",event_attendee_path(@event,attendee), method: :delete %>
	</li>
	<% end %>
</ul>
<%= link_to "new attendee",new_event_attendee_path(@event) %>

app/views/event_attendees/new.html.erb
<!--Restful綜合應用實作-->

<%= form_for @attendee, url: event_attendees_path(@event) do|f| %>
	<%= f.text_field :name %>
	<%= f.submit %>
<% end %>

app/views/event_attendees/show.html.erb
<!--Restful綜合應用實作-->

<p> <%= @attendee.name %> </p>