config/routes.rb
Rails.application.routes.draw do

    resources :events do
    
    resources :attendees , controller: "event_attendees"
    
    resource :location, controller: "event_locations"

    collection do
        get :latest
    end

    collection do
      post :bulk_delete
    end

    collection do
      post :bulk_update
    end

    member do
      get :dashboard
    end

    member do
      post :join
      post :withdraw
    end

  end

  resources :people #此為建立應架(scaffold)時自動產生

  get "/welcome/say_hello" => "welcome#say" 
  
  root "welcome#index"

  get "/welcome" => "welcome#index"
  

  namespace :admin do
    resources :events
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
	
	#關聯資料設計練習-1對多關聯
	has_many :attendees , ->{ where(["created_at > ?", Time.now - 7.day]).order("id DESC") } , dependent: :destroy #複數,串連where條件+指定順序為降序

	#關聯資料設計練習-1對1關聯
	has_one :location ,dependent: :destroy #單數,設定當物件刪除時也一起刪除依賴它的資料

	#關聯資料設計練習-多對多關聯
	has_many :event_groupships #複數
	has_many :groups, through: :event_groupships

	belongs_to :category

	#加入以下程式，就會有 @event.category_name 可以使用 而且允許 @event.category 是 nil
	#防止nil.name錯誤
	delegate :name,to: :category,prefix: true,allow_nil: true
	
	#accepts_nested_attributes_for這個方法可以讓更新event資料時 也可以直接更新location的關聯資料	
	#也就是說 可以完全不需要修改events_controller的新增和編輯Action
	#可以透過本來的params[:event]參數來新增或修改location
	accepts_nested_attributes_for :location,allow_destroy: true , reject_if: :all_blank

	validates_presence_of :name #宣告name屬性為必填(不可空白)
end

app/controllers/admin/events_controller.rb
#管理後台的controller
class Admin::EventsController < ApplicationController

	#簡單的http驗證
	before_action :authenticate
	layout "admin"

	#...

	protected

	def authenticate
		authenticate_or_request_with_http_basic do |user_name , password|
			user_name == "username" && password == "password"
		end		
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :set_event, only:[:show,:edit,:update,:destroy] 

	def index
		#一次抓出所有活動太耗效能
		#@events = Event.all

		#使用kaminari套件後改成
		#@events = Event.page(params[:page]).per(5)

=begin
		#使用respond_to支援不同的資料格式(XML JSON Atom)
		respond_to do |format|
			format.html # index.html.erb
			format.xml { render xml: @events.to_xml }
			format.json { render json: @events.to_json }
			format.atom {@feed_title = "my event list" } #index.atom.builder
		end
=end
		#關鍵字搜尋功能
		if params[:keyword]
			@events = Event.where( ["name like ?","%#{params[:keyword]}%" ] )
		else
			@events = Event.all
		end

		#使用kaminari套件做分頁拉到後面
		#先檢查是否有params[:keyword]參數來進行過濾 
		#最後統一進行分頁。
		#@events = @events.page(params[:page]).per(5)

		#讓event index可以照參數排序 (排序的參數在index.html.erb)
		sort_by = (params[:order] == "name") ? "name" : "created_at"
		@events = Event.order(sort_by).page(params[:page]).per(5)
		
		#支援不同資料格式一樣拉到後面 不然會產生錯誤
		respond_to do |format|
			format.html # index.html.erb
			format.xml { render xml: @events.to_xml }
			format.json { render json: @events.to_json }
			format.atom {@feed_title = "my event list" } #index.atom.builder
		end

	end

	def new
		@event = Event.new
	end

	def create
		#@event = Event.new(params[:event])
		@event = Event.new(event_params)
		if @event.save

			#改成Restful後註解掉改成
			#redirect_to action: :index
			redirect_to events_url

			flash[:notice] = "event was successfully created"
		else
			render action: :new
		end
	end

	def show
		#透過before_action 
		#可以將Controller中重複的程式獨立出來
		#以下此行可註解掉
		#@event = Event.find(params[:id]) 

		#改放在respond_to裡面
		#@page_title = @event.name
		respond_to do |format|
			format.html {@page_title = @event.name } #show.html.erb
			format.xml #show.xml.builder
			format.json { render json: {id: @event.id ,name: @event.name }.to_json}
		end
	end

	def edit
		#@event = Event.find(params[:id])
	end

	def update
		#@event = Event.find(params[:id])
		if @event.update(event_params)
			#改成Restful後註解掉改成
			#redirect_to action: :show, id: @event
			redirect_to event_url(@event)

			flash[:notice] = "event was successfully updated"
		else
			render action: :edit
		end
	end

	def destroy
		#@event = Event.find(params[:id])
		@event.destroy

		#改成Restful後註解掉改成
		#redirect_to action: :index		
		redirect_to events_url

		flash[:alert] = "event was successfully deleted"

	end

	def latest
		@events = Event.order("id DESC").limit(3)
	end

	#刪除多筆的方法
	def bulk_delete
		Event.destroy_all
		redirect_to events_path
	end

	def bulk_update
		ids = Array(params[:ids])
		events = ids.map{ |i| Event.find_by_id(i) }.compact

		if params[:commit] == "Publish"
			events.each{ |e| e.update( status: "published" )}

		elsif params[:commit] == "Delete"
			events.each{ |e| e.destroy }
		end

		redirect_to events_url
	end

	def dashboard
		@event = Event.find(params[:id])
	end

	def join
		@event = Event.find(params[:id])
		Membership.find_or_create_by(event: @event,user: current_user)	
		
		redirect_to :back
	end

	def withdraw
		@event = Event.find(params[:id])
		@membership = Membership.find_by(event: @event,user: current_user )
		@membership.destroy

		redirect_to :back
	end

	private

	def event_params
		params.require(:event).permit(:name, :description ,:category_id,location_attributes: [:id,:name,:_destroy],group_ids: [])
	end

	def set_event
		@event = Event.find(params[:id])
	end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
	def setup_event(event)
		event.build_location unless event.location
		event
	end
end

app/views/events/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>

<!--讓 event 可以用 select 單選一個 category 兩種寫法選一 效果一樣-->
<%= f.collection_select(:category_id,Category.all,:id,:name) %>
<!--
<%= f.select :category_id,Category.all.map { |c|[c.name,c.id]  } %>
-->

<!--在 event new/edit 中 可以使用 checkbox 多選 group 兩種寫法選一種 效果一樣(書)-->
<%= f.collection_check_boxes(:group_ids,Group.all ,:id,:name) %>



<%= f.fields_for :location do |location_form| %>
	<p>
		<%= location_form.label :name,"Location Name" %>
		<%= location_form.text_field :name %>

			<% unless location_form.object.new_record? %>
				<%= location_form.label :_destroy,"Remove；" %>
				<%= location_form.check_box :_destroy %>
			<% end %>
	</p>
<% end %>

<% if @event.errors.any? %>
	<ul>
		<% @event.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

app/views/events/edit.html.erb
<!--Restful--> 

<%= form_for @event, url: event_path(@event) , method: :patch do |f| %>
<!-- :url和:method可以省略 Rails自動會根據@event是新建的還是修改來決定要不要使用patch -->
<%= render partial: "form" , locals: {:f => f} %>
<%= f.submit "Update" %>

<% end %>

app/views/events/event.html.erb
<%= button_to "join" ,join_event_path(@event) %>
<%= button_to "withdraw" ,withdraw_event_path(@event) %>

app/views/events/index.html.erb
<!--讓event index可以進行關鍵字搜尋-->
<%= form_tag events_path, method: :get do %>
	<%= text_field_tag "keyword" %>
	<%= submit_tag "Search" %>
<% end %>


<!-- 使用kaminari分頁套件後加入: -->
<%= paginate @events %>

<ul>
	<% @events.each do |event| %>
	<li>

		<%= event.name %>
		<!--使用外卡路由 格式定義在routes-->
		<!--
		<button type="button" class="btn btn-success">
		<%= link_to "顯示", controller: "events" , action: "show" ,id: event %>
		</button>

		<button type="button" class="btn btn-primary">
		<%= link_to "編輯",controller: "events",action: "edit" , id: event %>
		</button>

		<button type="button" class="btn btn-danger">
		<%= link_to "刪除",controller: "events",action: "destroy", id:event %>
		</button>
		-->

		<!--使用Restful-->
		<%= link_to "show" , event_path(event) %>

		<!--加入其他格式的超連結-->
    	<%= link_to " (XML)", event_path(event, format: :xml) %>
    	<%= link_to " (JSON)", event_path(event, :format => :json) %>


		<%= link_to "edit" , edit_event_path(event) %>
		<%= button_to "delete" , event_path(event) , method: :delete , data: {confirm: "Are you sure?" }%>

		<!--Restful綜合應用實作-->
		<%= link_to "attendees", event_attendees_path(event) %>

		<%= link_to "location",event_location_path(event) %>

		<%= link_to "Dashboard" ,dashboard_event_path(event) %>

	</li>
	<% end %>
</ul>
<!--
<%= link_to "New Event", controller: "events",action: "new" %>
-->

<!--使用Restful-->
<%= link_to "New Event" , new_event_path %>
<br>
<!--加入其他格式的超連結-->
<%= link_to "Atom feed", events_path(:format => :atom) %>

<%= button_to "Delete All" , bulk_delete_events_path , method: :post %>

<%= link_to "sort by Name" , events_path(order: "name")%>
<%= link_to "sort by Default" ,events_path %>

<!--若要將此核取方塊與這條線之上程式合併 須刪除上面的delete 不然這裡的Delete功能會重複無法執行-->
<%= form_tag bulk_update_events_path do %>
<ul>
	<% @events.each do |e| %>
	<li>
		<%= check_box_tag "ids[]" ,e.id, false %>
		<%= e.name %>
	</li>
	<% end %>
</ul>
<%= submit_tag "Delete" %>
<%= submit_tag "Publish" %>
<% end %>

app/views/events/new.html.erb
<!--Restful-->

<!--<%= form_for @event, url: events_path do |f|  %>-->
<!--本例中可以完全省略:url參數 Rails可以根據@event推算出路由-->

<%= form_for setup_event(@event),url: events_path do |f| %>

	<%= render partial: "form", locals: {:f => f} %>
	<%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<!--
<p><%= link_to 'Back to index', controller: "events", action: "index" %></p>
-->

<!--Restful-->
<p><%= link_to "Back to index",events_path %></p>

<!--防止nil.name錯誤選單簡單方式 或 在Event model加入更改-->
<!--一般顯示方式用 @event.category.name -->
<p>Categroy:<%= @event.category.try(:name) %></p>


<!--顯示Group名稱-->
<p>
Group:
	<% @event.groups.each do |g| %>
		<%= g.name %>
	<% end %>
</p>